baseURL = "https://github.com/R0gerBradf0rd/CV_Svyat.github.io.git"
languageCode = "ru-ru"
title = "CV Иванова Ивановича"
theme = "beautifulhugo"

[params]
  description = "CV студента ПС 43 Иванова Ивановича"