baseURL = "https://github.com/R0gerBradf0rd/CV_Svyat.github.io"
languageCode = "ru-ru"
title = "CV Иванова Ивановича"
theme = "beautifulhugo"

[params]
  description = "CV студента ПС 43 Иванова Ивановича"

[module]
[[module.imports]]
    path = "github.com/halogenica/beautifulhugo"